import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import {Roboto } from "next/font/google";

const roboto = Roboto({
  subsets:["latin"],
  weight:["400","700"],
  variable:"--font-roboto"
})

export const metadata: Metadata = {
  title: "Dhanify - Smart Investing Made Easy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body>
        {children} 
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
